-- ============================================================
-- Trapnex Market Intelligence - Phase 6R DB Fix
-- Version: 6R.3
--
-- Purpose:
-- Fix existing/incomplete Phase 6R database schemas.
--
-- IMPORTANT:
-- This version intentionally DOES NOT create a foreign key
-- between snapshot rows and stock_intelligence_runs.
--
-- The application only requires run_id to be a UUID column.
-- Removing the FK avoids compatibility problems with an
-- existing/incomplete Supabase table.
-- ============================================================


-- ============================================================
-- 1. Run summary table
-- ============================================================

create table if not exists public.stock_intelligence_runs (
  run_id uuid primary key,
  started_at timestamptz not null,
  completed_at timestamptz not null,
  universe_size integer not null,
  ready_count integer not null,
  insufficient_count integer not null,
  error_count integer not null
);


-- ============================================================
-- 2. Snapshot table
--
-- If the table already exists, DO NOT recreate it.
-- We upgrade it column-by-column below.
-- ============================================================

create table if not exists public.stock_intelligence_run_factor_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid,
  symbol text,
  calculated_at timestamptz,
  score numeric,
  status text,
  confidence integer,
  factors jsonb,
  metadata jsonb
);


-- ============================================================
-- 3. Add missing columns safely
--
-- information_schema check is used instead of relying only on
-- CREATE TABLE IF NOT EXISTS.
-- ============================================================

do $$
begin

  -- run_id
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'run_id'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column run_id uuid;
  end if;


  -- symbol
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'symbol'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column symbol text;
  end if;


  -- calculated_at
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'calculated_at'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column calculated_at timestamptz;
  end if;


  -- score
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'score'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column score numeric;
  end if;


  -- status
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'status'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column status text;
  end if;


  -- confidence
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'confidence'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column confidence integer;
  end if;


  -- factors
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'factors'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column factors jsonb;
  end if;


  -- metadata
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stock_intelligence_run_factor_snapshots'
      and column_name = 'metadata'
  ) then
    alter table public.stock_intelligence_run_factor_snapshots
      add column metadata jsonb;
  end if;

end $$;


-- ============================================================
-- 4. Defaults for metadata
-- ============================================================

alter table public.stock_intelligence_run_factor_snapshots
  alter column metadata
  set default '{}'::jsonb;


-- ============================================================
-- 5. Indexes
-- ============================================================

create index if not exists
  stock_intelligence_run_factor_symbol_calculated_idx
on public.stock_intelligence_run_factor_snapshots
  (symbol, calculated_at desc);


create index if not exists
  stock_intelligence_run_factor_run_idx
on public.stock_intelligence_run_factor_snapshots
  (run_id);


-- ============================================================
-- 6. Verification
--
-- This should show run_id and all other required columns.
-- ============================================================

select
  column_name,
  data_type,
  is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'stock_intelligence_run_factor_snapshots'
order by ordinal_position;