-- Phase 6R DB compatibility migration
-- Safe to run after Phase 6P/6Q.
--
-- The previous Phase 6R draft used stock_factor_snapshots, which can collide
-- with an existing table created during an earlier attempt. This migration
-- intentionally uses a new, phase-specific table name.

create table if not exists stock_intelligence_runs (
  run_id uuid primary key,
  started_at timestamptz not null,
  completed_at timestamptz not null,
  universe_size integer not null,
  ready_count integer not null,
  insufficient_count integer not null,
  error_count integer not null
);

create table if not exists stock_intelligence_run_factor_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid not null
    references stock_intelligence_runs(run_id)
    on delete cascade,
  symbol text not null,
  calculated_at timestamptz not null,
  score numeric null,
  status text not null,
  confidence integer not null,
  factors jsonb not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists
  stock_intelligence_run_factor_symbol_calculated_idx
on stock_intelligence_run_factor_snapshots(symbol, calculated_at desc);

create index if not exists
  stock_intelligence_run_factor_run_idx
on stock_intelligence_run_factor_snapshots(run_id);

-- Do not modify the existing Phase 6P table:
-- stock_intelligence_factor_snapshots
-- It has a different, factor-per-row schema and remains valid.
