-- Phase 6S persistence additions.
-- Run after Phase 6R.
-- No foreign-key dependency is introduced.

create table if not exists public.stock_intelligence_data_quality_runs (
  run_id uuid primary key,
  started_at timestamptz not null,
  completed_at timestamptz not null,
  universe_size integer not null,
  ready_count integer not null,
  insufficient_count integer not null,
  error_count integer not null
);

create table if not exists public.stock_intelligence_data_quality_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid,
  symbol text not null,
  observed_at timestamptz not null,
  quality_score numeric null,
  providers jsonb not null default '{}'::jsonb,
  completeness jsonb not null default '{}'::jsonb,
  errors jsonb not null default '[]'::jsonb
);

create index if not exists stock_intelligence_dq_symbol_observed_idx
on public.stock_intelligence_data_quality_snapshots(symbol, observed_at desc);

create index if not exists stock_intelligence_dq_run_idx
on public.stock_intelligence_data_quality_snapshots(run_id);
