export const INDIA_LIQUID_UNIVERSE = [
  "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","ITC","SBIN","BHARTIARTL",
  "LT","AXISBANK","KOTAKBANK","M&M","MARUTI","SUNPHARMA","HINDUNILVR",
  "BAJFINANCE","TITAN","ADANIENT","ADANIPORTS","HCLTECH",
] as const;

export type UniverseSymbol = (typeof INDIA_LIQUID_UNIVERSE)[number];
